database:
  - db_name: sipaham
    db_password: ayambakarkecap212
    db_user: root
data:
  - location: /Users/denimarswandi/sumbawa
db_bak_folder: /Users/denimarswandi/project/sipaham/db-bak-bash/dbbak
